apiVersion: v2
name: auth-bundle
description: A Helm chart for Giant Swarm's collection of auth tools.
home: https://github.com/giantswarm/auth-bundle
icon: https://s.giantswarm.io/app-icons/athena/1/light.svg
sources:
  - https://github.com/giantswarm/auth-bundle
version: 0.5.0
annotations:
  io.giantswarm.application.audience: all
  io.giantswarm.application.team: shield
  io.giantswarm.application.app-type: bundle
